definitions:
  entities.Address:
    properties:
      city:
        example: Maua
        minLength: 2
        type: string
      complement:
        example: Perto do Mercado X
        type: string
      neighborhood:
        example: Jardins
        type: string
      postal_code:
        example: 123-45678
        maxLength: 9
        minLength: 8
        type: string
      state:
        example: SP
        type: string
      street:
        example: Rua teste
        type: string
    required:
    - city
    - neighborhood
    - postal_code
    - state
    - street
    type: object
  entities.Company:
    properties:
      address:
        $ref: '#/definitions/entities.Address'
      document:
        example: 19.862.056/0002-23
        maxLength: 18
        minLength: 14
        type: string
      fantasy_name:
        example: My Company
        type: string
      social_reason:
        example: My Company LTDA
        type: string
      total_employees:
        example: 100
        minimum: 0
        type: integer
      total_employees_pwd:
        example: 1
        minimum: 0
        type: integer
    required:
    - address
    - document
    - fantasy_name
    - social_reason
    type: object
  helpers.ErrorResponse:
    properties:
      error: {}
      success:
        example: false
        type: boolean
    type: object
  viewmodels.AddressOutput:
    properties:
      city:
        example: Maua
        type: string
      complement:
        example: Perto do Mercado X
        type: string
      neighborhood:
        example: Jardins
        type: string
      postal_code:
        example: 123-45678
        type: string
      state:
        example: SP
        type: string
      street:
        example: Rua teste
        type: string
    type: object
  viewmodels.CompaniesListResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/viewmodels.CompanyOutput'
        type: array
      success:
        type: boolean
    type: object
  viewmodels.CompanyBadRequestResponse:
    properties:
      error:
        example: 'Insufficient quota: company must have 10 PWD(s), but has 5 (required
          by Brazilian Law nº 8.213/91, art. 93)'
        type: string
      success:
        type: boolean
    type: object
  viewmodels.CompanyConflitResponse:
    properties:
      error:
        example: company already exists
        type: string
      success:
        type: boolean
    type: object
  viewmodels.CompanyCreatedResponse:
    properties:
      data:
        $ref: '#/definitions/viewmodels.CompanyOutput'
      success:
        type: boolean
    type: object
  viewmodels.CompanyNotFoundResponse:
    properties:
      error:
        example: company not found
        type: string
      success:
        type: boolean
    type: object
  viewmodels.CompanyOutput:
    properties:
      address:
        $ref: '#/definitions/viewmodels.AddressOutput'
      created_at:
        example: "2025-09-04T23:51:26.881469869Z"
        type: string
      document:
        example: "19862056000223"
        type: string
      fantasy_name:
        example: My Company
        type: string
      id:
        example: 68ba25fe8cd931d0437112ad
        type: string
      social_reason:
        example: My Company LTDA
        type: string
      total_employees:
        example: 100
        type: integer
      total_employees_pwd:
        example: 1
        type: integer
      updated_at:
        example: "2025-09-04T23:51:26.881469869Z"
        type: string
    type: object
  viewmodels.CompanyUpdatedResponse:
    properties:
      data:
        $ref: '#/definitions/viewmodels.CompanyOutput'
      success:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /api/companies:
    get:
      description: list all companies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/viewmodels.CompaniesListResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helpers.ErrorResponse'
      summary: list all companies
      tags:
      - Companies
    post:
      consumes:
      - application/json
      description: Create a new company in businessHub
      parameters:
      - description: Company Data
        in: body
        name: company
        required: true
        schema:
          $ref: '#/definitions/entities.Company'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/viewmodels.CompanyCreatedResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/viewmodels.CompanyBadRequestResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/viewmodels.CompanyConflitResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helpers.ErrorResponse'
      summary: create a new company
      tags:
      - Companies
  /api/companies/{id}:
    delete:
      description: delete a existing company in businessHub
      parameters:
      - description: Company ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/viewmodels.CompanyNotFoundResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helpers.ErrorResponse'
      summary: delete a existing company
      tags:
      - Companies
    put:
      consumes:
      - application/json
      description: edit a existing company in businessHub
      parameters:
      - description: Company Data
        in: body
        name: company
        required: true
        schema:
          $ref: '#/definitions/entities.Company'
      - description: Company ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/viewmodels.CompanyUpdatedResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/viewmodels.CompanyBadRequestResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/viewmodels.CompanyNotFoundResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helpers.ErrorResponse'
      summary: edit a existing company
      tags:
      - Companies
swagger: "2.0"
